name: Linux

on:
  pull_request:
  push:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    concurrency:
        group: ${{ github.ref }}-${{ github.base_ref }}-${{ github.head_ref }}-Linux
        cancel-in-progress: true
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: prepare local xmake
        run: cp -rf . ../xmake-source
      - uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: local#../xmake-source
      - uses: dlang-community/setup-dlang@v1
        with:
          compiler: dmd-latest
      - uses: little-core-labs/get-git-tag@v3.0.2
        id: tagName

      - name: Prepare
        run: |
          sudo apt update
          sudo apt install -y ruby ruby-dev rubygems build-essential llvm
          sudo apt install -y libgl1-mesa-dev libglu1-mesa-dev

      - name: Publish
        env:
          PPA_GPG_PRIKEY_2C0C68C9: ${{ secrets.PPA_GPG_PRIKEY_2C0C68C9 }}
        run: |
          # upload ubuntu/ppa
          sudo apt install -y dh-make rng-tools devscripts lintian
          echo "$PPA_GPG_PRIKEY_2C0C68C9" > ppa_gpg.key
          gpg --import ppa_gpg.key
          scripts/makeppa kinetic # 22.10
          scripts/makeppa jammy # 22.04
          scripts/makeppa focal # 20.04
          scripts/makeppa bionic # 18.04
          scripts/makeppa xenial # 16.04
          scripts/makeppa trusty # 14.04
